export interface AuthSetting {
  MAIL_POSTFIX: string;
  FEATURE_AVATAR_SOURCE: 'NO' | 'CONFLUENCE';
  FEATURE_AUTH_TYPE: 'PASSWORD' | 'LDAP';
  PRINT_COMPANY_NAME: string;
  PRINT_HEAD_MANAGER_POSITION: string;
  PRINT_HEAD_MANAGER_NAME: string;
}
